### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by dheckl** [EUROTRONIC-Technology/Spirit-ZigBee#8]
Thanks for posting the OTA update. Is it possible to publish the release notes?

**Comment by dako76** [comment]
Can/should i update my spirit zigbee with this version?

**Comment by jseebeck** [comment]
Thanks a lot for the work for the OTA update. I'd appreciate some release notes too.

Also I am confused about the version numbering. My spirits were shipped with firmware date code 20191014 whereas the published update has the lower code 20190408. 

Is it possible to publish the latest original firmware version too? I am hesitant to try the update when there is no possibility to go back to the original state in case something goes wrong. Or am I missing the option to backup the firmware in deconz?

**Comment by dheckl** [comment]
I have installed the firmware on one of my Spirit Zigbee Thermostats.

**Before**
Date Code: 20191014
HW Version: 35
Application Version: 22

**After**
Date Code: 20190408
HW Version: 34
Application Version: 18

**Comment by jeankone** [comment]
@dheckl expected that, because the firmware should be the one, before the "problematic" release. so any improvements for you?

**Comment by twsl** [comment]
Can anyone clear up the version differences @dheckl reported? Cause I noticed having a later version than the current release as well:

`    "device": {
        "applicationVersion": 18,
        "dateCode": "20190408",
        "friendlyName": "Therm 0xXXXX",
        "hardwareVersion": 34,
        "ieeeAddr": "0x00XXXX000192XXXX",
        "manufacturerID": 4151,
        "manufacturerName": "Eurotronic",
        "model": "SPZB0001",
        "networkAddress": 57003,
        "powerSource": "Battery",
        "softwareBuildID": "18181120",
        "stackVersion": 5,
        "type": "EndDevice",
        "zclVersion": 2
    },`

` "device": {
        "applicationVersion": 22,
        "dateCode": "20191014",
        "friendlyName": "Therm 0xXXXX",
        "hardwareVersion": 35,
        "ieeeAddr": "0x00XXXX0003c4XXXX",
        "manufacturerID": 4151,
        "manufacturerName": "Eurotronic",
        "model": "SPZB0001",
        "networkAddress": 48292,
        "powerSource": "Battery",
        "softwareBuildID": "22190930",
        "stackVersion": 5,
        "type": "EndDevice",
        "zclVersion": 2
    },`

**Comment by Mahai17** [comment]
> I have installed the firmware on one of my Spirit Zigbee Thermostats.
> 
> **Before**
> Date Code: 20191014
> HW Version: 35
> Application Version: 22
> 
> **After**
> Date Code: 20190408
> HW Version: 34
> Application Version: 18

@dheckl 
How did you install the new firmware?
When I hit the "update" button, it shows "idle". I wait hours, no progress.
It doesn't work for me. (Home Assistant, deconz)

**Comment by jeankone** [comment]
> > I have installed the firmware on one of my Spirit Zigbee Thermostats.
> > **Before**
> > Date Code: 20191014
> > HW Version: 35
> > Application Version: 22
> > **After**
> > Date Code: 20190408
> > HW Version: 34
> > Application Version: 18
> 
> @dheckl
> How did you install the new firmware?
> When I hit the "update" button, it shows "idle". I wait hours, no progress.
> It doesn't work for me. (Home Assistant, ConBee2, deconz)

same for me :/

**Comment by double1968** [comment]
Also for me the only thing that changes after the procedure is this:
but no update takes place.
![1](https://user-images.githubusercontent.com/48420012/106326866-79dea300-627d-11eb-8aa5-f4b185d46e79.JPG)

**Comment by fribse** [comment]
> When I hit the "update" button, it shows "idle". I wait hours, no progress.

On some of mine I had to hit update twice. You are sure that the thermostat you want to update is highlighted in the list, right?

**Comment by Mahai17** [comment]
> > When I hit the "update" button, it shows "idle". I wait hours, no progress.
> 
> On some of mine I had to hit update twice. You are sure that the thermostat you want to update is highlighted in the list, right?

Yes, I tried it a couple of times. (including, restart deconz, restart conbee2 stick, restart the Spirits, etc.)

**Comment by hackex** [comment]
> > > When I hit the "update" button, it shows "idle". I wait hours, no progress.
> > 
> > 
> > On some of mine I had to hit update twice. You are sure that the thermostat you want to update is highlighted in the list, right?
> 
> Yes, I tried it a couple of times. (including, restart deconz, restart conbee2 stick, restart the Spirits, etc.)
> What was your software starting point? The SW from Oct. 2019 (20191014)?

Hey, 
I have the same problem. I still do not understand if I can use the OTA instruction with deconz having the ZHA integration installed and running. Aren't both, deconz and ZHA, accessing the same Stick (in my case Dresden Conbee 2)? Could someone clarify this? Also, I only see my Eurotronic TVR in idle status in deconz and no update progress.

**Comment by magicdude4eva** [comment]
> I have the same problem. I still do not understand if I can use the OTA instruction with deconz having the ZHA integration installed and running. Aren't both, deconz and ZHA, accessing the same Stick (in my case Dresden Conbee 2)? Could someone clarify this? Also, I only see my Eurotronic TVR in idle status in deconz and no update progress.

I have zigbee2mqtt installed and in the past I installed deconz plugin so that I could flash the stick. I did the same now to flash the firmware - since I did not want to downgrade from 20191014, I stopped the upgrade of the old firmware when it was about 40% in.

**Comment by hackex** [comment]
> > I have the same problem. I still do not understand if I can use the OTA instruction with deconz having the ZHA integration installed and running. Aren't both, deconz and ZHA, accessing the same Stick (in my case Dresden Conbee 2)? Could someone clarify this? Also, I only see my Eurotronic TVR in idle status in deconz and no update progress.
> 
> I have zigbee2mqtt installed and in the past I installed deconz plugin so that I could flash the stick. I did the same now to flash the firmware - since I did not want to downgrade from 20191014, I stopped the upgrade of the old firmware when it was about 40% in.

Hi, thanks for the reply. Is it possible to have both applications run in parallel? In both, I need to set the serial device path? Is it possible that ZHA integration or zigbee2mqtt and deconz are accessing the same device?

**Comment by magicdude4eva** [comment]
I have not run both in parallel for a long time - i.e. more than 1 hour. I am not sure if something would collide here, but I could safely upgrade firmware.

**Comment by sygys** [comment]
I just received word from Eurotronic who advised me to flash the older firmware. There are errors in the newer version. 

I have no clue why they didnt just release a new firmware version and instead advise people to revert back to an older one.

Mine is around 50% now it takes ages.... when its finished i will do some tests if the trv_mode will stay 1. i noticed that the valve crashes multiple times a day when being on version 20191014. I hope this is fixed in the older version.

here is my log. This is what happens on the newer version of firmware:

```
debug 2022-01-19 10:54:41: Received MQTT message on 'zigbee2mqtt/Mancave thermostaatkraan/set' with data '{"valve_position":0}'
debug 2022-01-19 10:54:41: Publishing 'set' 'valve_position' to 'Mancave thermostaatkraan'


error 2022-01-19 10:55:04: Publish 'set' 'valve_position' to 'Mancave thermostaatkraan' failed: 'Error: Write 0x00158d00077434d9/1 hvacThermostat({"16385":{"value":0,"type":32}}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 14201 - 1 - 121 - 513 - 4 after 10000ms)'
debug 2022-01-19 10:55:04: Error: Write 0x00158d00077434d9/1 hvacThermostat({"16385":{"value":0,"type":32}}, {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 14201 - 1 - 121 - 513 - 4 after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
info  2022-01-19 10:55:04: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"Publish 'set' 'valve_position' to 'Mancave thermostaatkraan' failed: 'Error: Write 0x00158d00077434d9/1 hvacThermostat({\"16385\":{\"value\":0,\"type\":32}}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":true,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":4151,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 14201 - 1 - 121 - 513 - 4 after 10000ms)'","meta":{"friendly_name":"Mancave thermostaatkraan"},"type":"zigbee_publish_error"}'

debug 2022-01-19 10:55:14: Device 'Mancave thermostaatkraan' announced itself
info  2022-01-19 10:55:14: MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"Mancave thermostaatkraan","ieee_address":"0x00158d00077434d9"},"type":"device_announce"}'
info  2022-01-19 10:55:14: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"Mancave thermostaatkraan"},"type":"device_announced"}'

debug 2022-01-19 10:55:15: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"16387":2000,"16392":1}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:15: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":20,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":27.5,"occupied_heating_setpoint":30,"pi_heating_demand":10,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:15: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2000,"occupiedHeatingSetpoint":2000,"pIHeatingDemand":255,"unoccupiedHeatingSetpoint":2000}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:15: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":20,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":20,"occupied_heating_setpoint":20,"pi_heating_demand":100,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":20,"update":{"state":"idle"},"update_available":false,"valve_position":null}'

debug 2022-01-19 10:55:16: Retrieving state of 'Mancave thermostaatkraan' after reconnect
debug 2022-01-19 10:55:17: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2700,"occupiedHeatingSetpoint":3000,"pIHeatingDemand":13,"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:17: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":20,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":57,"local_temperature":27,"occupied_heating_setpoint":30,"pi_heating_demand":5,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:17: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"16387":3000}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:17: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":30,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":27,"occupied_heating_setpoint":30,"pi_heating_demand":5,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:17: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2700,"occupiedHeatingSetpoint":3000,"pIHeatingDemand":13,"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:17: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":30,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":27,"occupied_heating_setpoint":30,"pi_heating_demand":5,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:17: Received Zigbee message from 'Mancave thermostaatkraan', type 'attributeReport', cluster 'hvacThermostat', data '{"localTemp":2700,"occupiedHeatingSetpoint":3000,"pIHeatingDemand":13,"unoccupiedHeatingSetpoint":1600}' from endpoint 1 with groupID 0
info  2022-01-19 10:55:17: MQTT publish: topic 'zigbee2mqtt/Mancave thermostaatkraan', payload '{"battery":100,"battery_low":false,"current_heating_setpoint":30,"eurotronic_error_status":0,"eurotronic_host_flags":{"boost":false,"child_protection":false,"mirror_display":false,"window_open":false},"eurotronic_system_mode":1,"linkquality":60,"local_temperature":27,"occupied_heating_setpoint":30,"pi_heating_demand":5,"running_state":null,"system_mode":"auto","trv_mode":null,"unoccupied_heating_setpoint":16,"update":{"state":"idle"},"update_available":false,"valve_position":null}'
debug 2022-01-19 10:55:19: Received Zigbee message from 'Zolder kachel smartplug', type 'attributeReport', cluster 'seMetering', data '{"currentSummDelivered":[0,63584]}' from endpoint 1 with groupID 0
```

It crashes, reboots, anounces itself again en reconnects to the network. normally you wouldnt notice much when it does this. but if you are using direct valve mode this crash will set the value back to 2 in which you do no longer have control over the valve
